source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target 'NotTwitter' do
    platform :ios, '9.0'
    pod 'Peek', :path => '../', :configurations => ['Debug']
end
