source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Peek-Example' do
    platform :ios, '8.0'
    
    pod 'Peek', :path => '../', :configurations => ['Debug']
    pod 'OpenSans'
    pod 'pop'
    pod 'SPXMasking', '1.1.0'
end
